services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log

  # homeassistant:
  #   # container_name: homeassistant
  #   image: "ghcr.io/home-assistant/home-assistant:stable"
  #   expose:
  #     - 8123
  #   ports:
  #     - "8123:8123"
  #   volumes:
  #     - ha-config:/config
  #     - /etc/localtime:/etc/localtime:ro
  #     - /run/dbus:/run/dbus:ro
  #   restart: unless-stopped

volumes:
  mqtt-data:
  mqtt-log:
  ha-config:
